# A - mass nuber, Z - number of protons, N - numbers of neutrons, E_binding - binding energy of atomic nuclei
# E_lvl - for the future update, take into account energy levels


# "AXX": {"Atom_mass": 0,
#         "Z": 0,
#         "N": 0,
#         "Mass_amu": 0,
#         "Mass_exc": 0,
#         "stable": "stable/particle_unstable/beta_unstable",
#         "Energy_lvl":
#             {"0":
#                  {"E_x": 0, "E_x_err_kev": 0, "J": 0, "pi": 0, "T": 0, "G": 0, "G_err": 0},
#              "1":
#                  {"E_x": 0, "E_x_err_kev": 0, "J": 0, "pi": 0, "T": 0, "G": 0, "G_err": 0},
#              "2":
#                  {"E_x": 0, "E_x_err_kev": 0, "J": 0, "pi": 0, "T": 0, "G": 0, "G_err": 0},
#              "3":
#                  {"E_x": 0, "E_x_err_kev": 0, "J": 0, "pi": 0, "T": 0, "G": 0, "G_err": 0},
#              "4":
#                  {"E_x": 0, "E_x_err_kev": 0, "J": 0, "pi": 0, "T": 0, "G": 0, "G_err": 0},
#              "5":
#                  {"E_x": 0, "E_x_err_kev": 0, "J": 0, "pi": 0, "T": 0, "G": 0, "G_err": 0},
#              "6":
#                  {"E_x": 0, "E_x_err_kev": 0, "J": 0, "pi": 0, "T": 0, "G": 0, "G_err": 0},
#              "7":
#                  {"E_x": 0, "E_x_err_kev": 0, "J": 0, "pi": 0, "T": 0, "G": 0, "G_err": 0},
#              "8":
#                  {"E_x": 0, "E_x_err_kev": 0, "J": 0, "pi": 0, "T": 0, "G": 0, "G_err": 0},
#              "9":
#                  {"E_x": 0, "E_x_err_kev": 0, "J": 0, "pi": 0, "T": 0, "G": 0, "G_err": 0}
#              },
#         "Phase_volume":
#                 {"0":
#                      {"phase_particles": ["XX", "XX"], "ratios": [1, 1], "E_th_phase": 0},
#                  "1":
#                      {"phase_particles": ["XX", "XX"], "ratios": [1, 1], "E_th_phase": 0},
#                  "2":
#                      {"phase_particles": ["XX", "XX"], "ratios": [1, 1], "E_th_phase": 0}
#                  }
#         },

dict_particles = {
    "nn": {
        "Atom_mass": 1,
        "Z": 0,
        "N": 1,
        "Mass_MeV": 939.565,
        "Mass_amu": 1.008664,
        "E_binding": 7.28897059,
        "Energy_lvl": {"0": {"E_x": 0, "J": 0.5, "pi": 1, "T": -0.5}},
        "Phase_volume": {"0": None},
    },
    "1H": {
        "Atom_mass": 1,
        "Z": 1,
        "N": 0,
        "Mass_MeV": 938.272,
        "Mass_amu": 1.007825,
        "E_binding": 7.28897059,
        "Energy_lvl": {"0": {"E_x": 0, "J": 0.5, "pi": 1, "T": 0.5}},
        "Phase_volume": {"0": None},
    },
    "2H": {
        "Atom_mass": 2,
        "Z": 1,
        "N": 1,
        "Mass_MeV": 1864.70160702,
        "Mass_amu": 2.014102,
        "E_binding": 13.13572174,
        "Energy_lvl": {"0": {"E_x": 0, "J": 1, "pi": 1, "T": None}},
        "Phase_volume": {"0": None},
    },
    "3H": {
        "Atom_mass": 3,
        "Z": 1,
        "N": 2,
        "Mass_MeV": 2802.45285303,
        "Mass_amu": 3.016050,
        "E_binding": 14.94980611,
        "Energy_lvl": {"0": {"E_x": 0, "J": 0.5, "pi": 1, "T": None}},
        "Phase_volume": {"0": None},
    },
    "4H": {
        "Atom_mass": 4,
        "Z": 1,
        "N": 3,
        "Mass_MeV": 3732.34686652,
        "Mass_amu": 4.02643,
        "E_binding": 24.621123,
        "Energy_lvl": {
            "0": {"E_x": 0, "J": 2, "pi": -1, "T": 1, "G": 5.42},
            "1": {"E_x": 0.31, "J": 1, "pi": -1, "T": 1, "G": 6.73},
            "2": {"E_x": 2.08, "J": 0, "pi": -1, "T": 1, "G": 8.92},
            "3": {"E_x": 2.83, "J": 1, "pi": -1, "T": 1, "G": 12.99},
        },
        "Phase_volume": {
            "0": {"phase_particles": ["3H", "nn"], "ratios": [1, 1], "E_th_phase": 0},
            "1": {
                "phase_particles": ["2H", "nn"],
                "ratios": [1, 2],
                "E_th_phase": 6.257,
            },
            "2": {
                "phase_particles": ["1H", "nn"],
                "ratios": [1, 3],
                "E_th_phase": 8.481,
            },
        },
    },
    "5H": {
        "Atom_mass": 5,
        "Z": 1,
        "N": 4,
        "Mass_MeV": 4663.6408799,
        "Mass_amu": 5.03531,
        "E_binding": 32.89244,
        "Energy_lvl": {
            "0": {"E_x": 0, "J": 0.5, "pi": 1, "T": None},
            "1": {"E_x": 3.1, "J": None, "pi": None, "T": None},
            "2": {"E_x": 8.1, "J": None, "pi": None, "T": None},
            "3": {"E_x": 16.1, "J": None, "pi": None, "T": None},
            "4": {"E_x": 24.4, "J": None, "pi": None, "T": None},
        },
        "Phase_volume": {"0": None},
    },
    "6H": {
        "Atom_mass": 6,
        "Z": 1,
        "N": 5,
        "Mass_MeV": 5594.22293328,
        "Mass_amu": 6.04496,
        "E_binding": 41.875717,
        "Energy_lvl": {
            "0": {"E_x": 0, "J": None, "pi": None, "T": None},
            "1": {"E_x": 4.1, "J": None, "pi": None, "T": None},
            "2": {"E_x": 8.0, "J": None, "pi": None, "T": None},
            "3": {"E_x": 12.3, "J": None, "pi": None, "T": None},
            "4": {"E_x": 18.7, "J": None, "pi": None, "T": None},
        },
        "Phase_volume": {
            "0": {"phase_particles": ["3H", "nn"], "ratios": [1, 3], "E_th_phase": -2.7}
        },
    },
    "7H": {
        "Atom_mass": 7,
        "Z": 1,
        "N": 6,
        "Mass_MeV": 6526.528980659999,
        "Mass_amu": 7.052750,
        "E_binding": 49.135,
        "Energy_lvl": {
            "0": {"E_x": 0, "J": 0.5, "pi": 1, "T": None},
            "1": {"E_x": 15, "J": None, "pi": None, "T": None},
            "2": {"E_x": 20, "J": None, "pi": None, "T": None},
        },
        "Phase_volume": {"0": None},
    },
    "3He": {
        "Atom_mass": 3,
        "Z": 2,
        "N": 1,
        "Mass_MeV": 2801.17811163,
        "Mass_amu": 3.016030,
        "E_binding": 14.93121551,
        "Energy_lvl": {
            "0": {"E_x": 0, "J": 0.5, "pi": 1, "T": None, "G": 0},
        },
        "Phase_volume": {"0": None},
    },
    "4He": {
        "Atom_mass": 4,
        "Z": 2,
        "N": 2,
        "Mass_MeV": 3753.24974191,
        "Mass_amu": 4.002603,
        "E_binding": 2.42491561,
        "Energy_lvl": {
            "0": {"E_x": 0, "J": 0, "pi": 1, "T": 0, "G": 0},
            "1": {"E_x": 20.21, "J": 0, "pi": 1, "T": 0, "G": 0.5},
            "2": {"E_x": 21.01, "J": 0, "pi": -1, "T": 0, "G": 0.84},
            "3": {"E_x": 21.84, "J": 2, "pi": -1, "T": 0, "G": 2.01},
            "4": {"E_x": 23.33, "J": 2, "pi": -1, "T": 1, "G": 5.01},
            "5": {"E_x": 23.64, "J": 1, "pi": -1, "T": 1, "G": 6.2},
            "6": {"E_x": 24.25, "J": 1, "pi": -1, "T": 0, "G": 6.1},
            "7": {"E_x": 25.28, "J": 0, "pi": -1, "T": 1, "G": 7.97},
            "8": {"E_x": 25.95, "J": 1, "pi": -1, "T": 1, "G": 12.66},
            "9": {"E_x": 27.42, "J": 2, "pi": 1, "T": 0, "G": 8.69},
            "10": {"E_x": 28.31, "J": 1, "pi": 1, "T": 0, "G": 9.89},
            "11": {"E_x": 28.37, "J": 1, "pi": -1, "T": 0, "G": 3.92},
            "12": {"E_x": 28.39, "J": 2, "pi": -1, "T": 1, "G": 8.75},
            "13": {"E_x": 28.64, "J": 0, "pi": -1, "T": 0, "G": 4.89},
            "14": {"E_x": 28.67, "J": 2, "pi": 1, "T": 0, "G": 3.78},
            "15": {"E_x": 29.89, "J": 2, "pi": 1, "T": 0, "G": 9.72},
        },
        "Phase_volume": {
            "0": {
                "phase_particles": ["3H", "1H"],
                "ratios": [1, 1],
                "E_th_phase": 19.815,
            },
            "1": {
                "phase_particles": ["3He", "nn"],
                "ratios": [1, 1],
                "E_th_phase": 20.578,
            },
            "2": {
                "phase_particles": ["2H", "2H"],
                "ratios": [1, 1],
                "E_th_phase": 23.848,
            },
            "3": {
                "phase_particles": ["2H", "nn", "1H"],
                "ratios": [1, 1, 1],
                "E_th_phase": 26.072,
            },
            "4": {
                "phase_particles": ["nn", "1H"],
                "ratios": [2, 2],
                "E_th_phase": 28.296,
            },
        },
    },
    "5He": {
        "Atom_mass": 5,
        "Z": 2,
        "N": 3,
        "Mass_MeV": 4683.8537549,
        "Mass_amu": 5.012057,
        "E_binding": 11.386233,
        "Energy_lvl": {
            "0": {
                "E_x": 0,
                "E_x_err_kev": 0,
                "J": 1.5,
                "pi": -1,
                "T": 0.5,
                "G": 0.648,
                "G_err": 0,
            },
            "1": {
                "E_x": 1.27,
                "E_x_err_kev": 0,
                "J": 0.5,
                "pi": -1,
                "T": 0.5,
                "G": 5.57,
                "G_err": None,
            },
            "2": {
                "E_x": 16.84,
                "E_x_err_kev": 0,
                "J": 1.5,
                "pi": 1,
                "T": 0.5,
                "G": 0.0745,
                "G_err": None,
            },
            "3": {
                "E_x": 19.14,
                "E_x_err_kev": 0,
                "J": 2.5,
                "pi": 1,
                "T": 0.5,
                "G": 3.56,
                "G_err": None,
            },
            "4": {
                "E_x": 19.26,
                "E_x_err_kev": 0,
                "J": 1.5,
                "pi": 1,
                "T": 0.5,
                "G": 3.96,
                "G_err": None,
            },
            "5": {
                "E_x": 19.31,
                "E_x_err_kev": 0,
                "J": 3.5,
                "pi": 1,
                "T": 0.5,
                "G": 3.02,
                "G_err": None,
            },
            "6": {
                "E_x": 19.96,
                "E_x_err_kev": 0,
                "J": 1.5,
                "pi": -1,
                "T": 0.5,
                "G": 1.92,
                "G_err": None,
            },
            "7": {
                "E_x": 21.25,
                "E_x_err_kev": 0,
                "J": 1.5,
                "pi": 1,
                "T": 0.5,
                "G": 4.61,
                "G_err": None,
            },
            "8": {
                "E_x": 21.39,
                "E_x_err_kev": 0,
                "J": 2.5,
                "pi": 1,
                "T": 0.5,
                "G": 3.95,
                "G_err": None,
            },
            "9": {
                "E_x": 21.64,
                "E_x_err_kev": 0,
                "J": 0.5,
                "pi": 1,
                "T": 0.5,
                "G": 4.03,
                "G_err": None,
            },
            "10": {
                "E_x": 23.97,
                "E_x_err_kev": 0,
                "J": 3.5,
                "pi": 1,
                "T": 0.5,
                "G": 5.44,
                "G_err": None,
            },
            "11": {
                "E_x": 24.06,
                "E_x_err_kev": 0,
                "J": 2.5,
                "pi": -1,
                "T": 0.5,
                "G": 5.23,
                "G_err": None,
            },
        },
        "Phase_volume": {
            "0": {
                "phase_particles": ["4He", "nn"],
                "ratios": [1, 1],
                "E_th_phase": -0.798,
            },
            "1": {
                "phase_particles": ["3H", "2H"],
                "ratios": [1, 1],
                "E_th_phase": 16.792,
            },
            "2": {
                "phase_particles": ["3H", "1H", "nn"],
                "ratios": [1, 1, 1],
                "E_th_phase": 19.016,
            },
            "3": {
                "phase_particles": ["3He", "nn"],
                "ratios": [1, 2],
                "E_th_phase": 19.78,
            },
        },
    },
    "6He": {
        "Atom_mass": 6,
        "Z": 2,
        "N": 4,
        "Mass_MeV": 5617.2132232799995,
        "Mass_amu": 6.018889124,
        "E_binding": 17.592095,
        "Energy_lvl": {
            "0": {
                "E_x": 0,
                "E_x_err_kev": 0,
                "J": 0,
                "pi": 1,
                "T": 1,
                "G": 0,
                "G_err": 0,
            },
            "1": {
                "E_x": 1.797,
                "E_x_err_kev": 25,
                "J": 2,
                "pi": 1,
                "T": 1,
                "G": 0.113,
                "G_err": 0.113,
            },
            "2": {
                "E_x": 5.6,
                "E_x_err_kev": 300,
                "J": [2, 1, 0],
                "pi": [1, -1, 1],
                "T": 1,
                "G": 12.1,
                "G_err": 1.1,
            },
            "3": {
                "E_x": 14.6,
                "E_x_err_kev": 0.7,
                "J": [1, 2],
                "pi": [-1, -1],
                "T": 1,
                "G": 7.4,
                "G_err": 1,
            },
            "4": {
                "E_x": 15.5,
                "E_x_err_kev": 500,
                "J": None,
                "pi": None,
                "T": None,
                "G": 4,
                "G_err": 2,
            },
            "5": {
                "E_x": 23.3,
                "E_x_err_kev": 1,
                "J": None,
                "pi": None,
                "T": None,
                "G": 14.8,
                "G_err": 2.3,
            },
            "6": {
                "E_x": 32,
                "E_x_err_kev": None,
                "J": None,
                "pi": None,
                "T": None,
                "G": 2,
                "G_err": None,
            },
            "7": {
                "E_x": 36,
                "E_x_err_kev": None,
                "J": None,
                "pi": None,
                "T": None,
                "G": 2,
                "G_err": None,
            },
        },
        "Phase_volume": {
            "0": {"phase_particles": ["4He", "2H"], "ratios": [1, 1], "E_th_phase": 0},
            "1": {
                "phase_particles": ["4He", "nn"],
                "ratios": [1, 2],
                "E_th_phase": 0.973,
            },
            "2": {
                "phase_particles": ["4He", "nn"],
                "ratios": [1, 1],
                "E_th_phase": 1.771,
            },
            "3": {
                "phase_particles": ["3H", "3H"],
                "ratios": [1, 1],
                "E_th_phase": 12.305,
            },
        },
    },
    "7He": {
        "Atom_mass": 7,
        "Z": 2,
        "N": 5,
        "Mass_MeV": 6548.29752266,
        "Mass_amu": 7.027991,
        "E_binding": 26.073126,
        "Energy_lvl": {
            "0": {
                "E_x": 0,
                "E_x_err_kev": 0,
                "J": 1.5,
                "pi": -1,
                "T": 1.5,
                "G": 0.15,
                "G_err": 0.02,
            },
            "1": {
                "E_x": 2.92,
                "E_x_err_kev": 90,
                "J": 2.5,
                "pi": -1,
                "T": 1,
                "G": 1.99,
                "G_err": 0.17,
            },
            "2": {
                "E_x": 5.8,
                "E_x_err_kev": 300,
                "J": None,
                "pi": None,
                "T": 1,
                "G": 4,
                "G_err": 1,
            },
        },
        "Phase_volume": {
            "0": {
                "phase_particles": ["6He", "nn"],
                "ratios": [1, 1],
                "E_th_phase": -0.445,
            },
            "1": {
                "phase_particles": ["4He", "nn"],
                "ratios": [1, 3],
                "E_th_phase": 0.529,
            },
            "2": {
                "phase_particles": ["5He", "nn"],
                "ratios": [1, 2],
                "E_th_phase": 1.327,
            },
        },
    },
    "8He": {
        "Atom_mass": 8,
        "Z": 2,
        "N": 6,
        "Mass_MeV": 7482.3262980399995,
        "Mass_amu": 8.03393439,
        "E_binding": 31.609681,
        "Energy_lvl": {
            "0": {
                "E_x": 0,
                "E_x_err_kev": 0,
                "J": 0,
                "pi": 1,
                "T": 2,
                "G": 0,
                "G_err": 0,
            },
            "1": {
                "E_x": [2.7, 3.6],
                "E_x_err_kev": None,
                "J": 1.5,
                "pi": 1,
                "T": None,
                "G": 0.6,
                "G_err": 0.2,
            },
            "2": {
                "E_x": 4.36,
                "E_x_err_kev": 0,
                "J": 1.5,
                "pi": -1,
                "T": None,
                "G": 1.3,
                "G_err": 0.5,
            },
            "3": {
                "E_x": 6.03,
                "E_x_err_kev": 0,
                "J": 1.5,
                "pi": None,
                "T": None,
                "G": 0.15,
                "G_err": 0.15,
            },
            "4": {
                "E_x": 7.16,
                "E_x_err_kev": 0,
                "J": 1.5,
                "pi": -1,
                "T": None,
                "G": 0.1,
                "G_err": 0.1,
            },
        },
        "Phase_volume": {
            "0": {
                "phase_particles": ["6He", "nn"],
                "ratios": [1, 2],
                "E_th_phase": 2.140,
            },
            "1": {
                "phase_particles": ["7He", "nn"],
                "ratios": [1, 1],
                "E_th_phase": 2.574,
            },
            "2": {
                "phase_particles": ["4He", "nn"],
                "ratios": [1, 4],
                "E_th_phase": 3.112184,
            },
        },
    },
    "9He": {
        "Atom_mass": 9,
        "Z": 2,
        "N": 7,
        "Mass_MeV": 0,
        "Mass_amu": 9.043946,
        "E_binding": 40.935,
        "Energy_lvl": {
            "0": {
                "E_x": 0,
                "E_x_err_kev": 0,
                "J": 0.5,
                "pi": 1,
                "T": 2.5,
                "G": 0,
                "G_err": 0,
            }
        },
        "Phase_volume": {
            "0": {
                "phase_particles": ["8He", "nn"],
                "ratios": [1, 1],
                "E_th_phase": -0.1007,
            }
        },
    },
    "10He": {
        "Atom_mass": 10,
        "Z": 2,
        "N": 8,
        "Mass_MeV": 0,
        "Mass_amu": 10.052815,
        "E_binding": 49.197,
        "Energy_lvl": {
            "0": {
                "E_x": 0,
                "E_x_err_kev": 0,
                "J": 0,
                "pi": 1,
                "T": 3,
                "G": 0.3,
                "G_err": 0.2,
            },
            "1": {
                "E_x": 3.24,
                "E_x_err_kev": 200,
                "J": 2,
                "pi": 1,
                "T": 3,
                "G": 1,
                "G_err": 0.3,
            },
            "2": {
                "E_x": 6.8,
                "E_x_err_kev": 70,
                "J": 3,
                "pi": -1,
                "T": 3,
                "G": 0.6,
                "G_err": 0.3,
            },
        },
        "Phase_volume": {
            "0": {
                "phase_particles": ["8He", "nn"],
                "ratios": [1, 2],
                "E_th_phase": -1.069,
            }
        },
    },
    "4Li": {
        "Atom_mass": 4,
        "Z": 3,
        "N": 1,
        "Mass_MeV": 3729.05813952,
        "Mass_amu": 4.02719,
        "E_binding": 25.323186,
        "Energy_lvl": {
            "0": {"E_x": 0, "J": 2, "pi": -1, "T": 1, "G": 6.03},
            "1": {"E_x": 0.32, "J": 1, "pi": -1, "T": 1, "G": 7.35},
            "2": {"E_x": 2.08, "J": 0, "pi": -1, "T": 1, "G": 9.35},
            "3": {"E_x": 2.85, "J": 1, "pi": -1, "T": 1, "G": 13.51},
        },
        "Phase_volume": {
            "0": {"phase_particles": ["3He", "1H"], "ratios": [1, 1], "E_th_phase": 0},
            "1": {
                "phase_particles": ["2H", "1H"],
                "ratios": [1, 2],
                "E_th_phase": 5.494,
            },
            "2": {
                "phase_particles": ["nn", "1H"],
                "ratios": [1, 3],
                "E_th_phase": 7.718,
            },
        },
    },
    "5Li": {
        "Atom_mass": 5,
        "Z": 3,
        "N": 2,
        "Mass_MeV": 4682.2677699000005,
        "Mass_amu": 5.012540,
        "E_binding": 11.678886,
        "Energy_lvl": {
            "0": {
                "E_x": 0,
                "E_x_err_kev": 0,
                "J": 1.5,
                "pi": -1,
                "T": 0.5,
                "G": 1.23,
                "G_err": 0,
            },
            "1": {
                "E_x": 1.49,
                "E_x_err_kev": 0,
                "J": 0.5,
                "pi": -1,
                "T": 0.5,
                "G": 6.60,
                "G_err": 0,
            },
            "2": {
                "E_x": 16.87,
                "E_x_err_kev": 0,
                "J": 1.5,
                "pi": 1,
                "T": 0.5,
                "G": 0.267,
                "G_err": 0,
            },
            "3": {
                "E_x": 19.28,
                "E_x_err_kev": 0,
                "J": 1.5,
                "pi": -1,
                "T": 0.5,
                "G": 0.959,
                "G_err": 0,
            },
            "4": {
                "E_x": 19.45,
                "E_x_err_kev": 0,
                "J": 3.5,
                "pi": 1,
                "T": 0.5,
                "G": 3.28,
                "G_err": 0,
            },
            "5": {
                "E_x": 19.71,
                "E_x_err_kev": 0,
                "J": 2.5,
                "pi": 1,
                "T": 0.5,
                "G": 4.31,
                "G_err": 0,
            },
            "6": {
                "E_x": 20.53,
                "E_x_err_kev": 0,
                "J": 0.5,
                "pi": 1,
                "T": 0.5,
                "G": 5.0,
                "G_err": 0,
            },
            "7": {
                "E_x": 22.06,
                "E_x_err_kev": 0,
                "J": 2.5,
                "pi": -1,
                "T": 0.5,
                "G": 15.5,
                "G_err": 0,
            },
            "8": {
                "E_x": 23.74,
                "E_x_err_kev": 0,
                "J": 2.5,
                "pi": 1,
                "T": 0.5,
                "G": 5.43,
                "G_err": 0,
            },
            "9": {
                "E_x": 25.42,
                "E_x_err_kev": 0,
                "J": 1.5,
                "pi": 1,
                "T": 0.5,
                "G": 0.534,
                "G_err": 0,
            },
            "10": {
                "E_x": 25.44,
                "E_x_err_kev": 0,
                "J": 3.5,
                "pi": 1,
                "T": 0.5,
                "G": 2.63,
            },
            "11": {
                "E_x": 32.53,
                "E_x_err_kev": 0,
                "J": 0.5,
                "pi": -1,
                "T": 0.5,
                "G": 35.7,
            },
        },
        "Phase_volume": {
            "0": {
                "phase_particles": ["4He", "1H"],
                "ratios": [1, 1],
                "E_th_phase": -1.69,
            },
            "1": {
                "phase_particles": ["3He", "1H"],
                "ratios": [1, 1],
                "E_th_phase": 16.66,
            },
            "2": {
                "phase_particles": ["3H", "1H"],
                "ratios": [1, 2],
                "E_th_phase": 18.12,
            },
            "3": {
                "phase_particles": ["3He", "nn", "1H"],
                "ratios": [1, 1, 1],
                "E_th_phase": 18.89,
            },
        },
    },
    "6Li": {
        "Atom_mass": 6,
        "Z": 3,
        "N": 3,
        "Mass_MeV": 5619.42510735,
        "Mass_amu": 6.0151228874,
        "E_binding": 14.08687893,
        "Energy_lvl": {
            "0": {
                "E_x": 0,
                "E_x_err_kev": 0,
                "J": 1,
                "pi": 1,
                "T": 0,
                "G": 0,
                "G_err": 0,
            },
            "1": {
                "E_x": 2.186,
                "E_x_err_kev": 2,
                "J": 3,
                "pi": 1,
                "T": 0,
                "G": 0.024,
                "G_err": 0.002,
            },
            "2": {
                "E_x": 3.56288,
                "E_x_err_kev": 0.10,
                "J": 0,
                "pi": 1,
                "T": 1,
                "G": 0.000008,
                "G_err": 0.0000002,
            },
            "3": {
                "E_x": 4.312,
                "E_x_err_kev": 22,
                "J": 2,
                "pi": 1,
                "T": 0,
                "G": 1.3,
                "G_err": 0.1,
            },
            "4": {
                "E_x": 5.366,
                "E_x_err_kev": 15,
                "J": 2,
                "pi": 1,
                "T": 1,
                "G": 0.541,
                "G_err": 0.02,
            },
            "5": {
                "E_x": 5.65,
                "E_x_err_kev": 50,
                "J": 1,
                "pi": 1,
                "T": 0,
                "G": 1.5,
                "G_err": 0.2,
            },
            "6": {
                "E_x": 17.985,
                "E_x_err_kev": 25,
                "J": 2,
                "pi": -1,
                "T": 1,
                "G": 3.012,
                "G_err": 0.007,
            },
            "7": {
                "E_x": 24.779,
                "E_x_err_kev": 54,
                "J": 3,
                "pi": -1,
                "T": 1,
                "G": 6.754,
                "G_err": 0.110,
            },
            "8": {
                "E_x": 24.890,
                "E_x_err_kev": 55,
                "J": 4,
                "pi": -1,
                "T": 1,
                "G": 5.316,
                "G_err": 0.112,
            },
            "9": {
                "E_x": 26.59,
                "E_x_err_kev": 65,
                "J": 2,
                "pi": -1,
                "T": 1,
                "G": 8.684,
                "G_err": 0.125,
            },
        },
        "Phase_volume": {
            "0": {
                "phase_particles": ["4He", "2H"],
                "ratios": [1, 1],
                "E_th_phase": 1.4743,
            },
            "1": {
                "phase_particles": ["5He", "1H"],
                "ratios": [1, 1],
                "E_th_phase": 4.497,
            },
            "2": {
                "phase_particles": ["5Li", "nn"],
                "ratios": [1, 1],
                "E_th_phase": 5.39,
            },
            "3": {
                "phase_particles": ["3H", "3He"],
                "ratios": [1, 1],
                "E_th_phase": 15.7947,
            },
            "4": {
                "phase_particles": ["3H", "2H", "1H"],
                "ratios": [1, 1, 1],
                "E_th_phase": 21.2881,
            },
            "5": {
                "phase_particles": ["3He", "1H", "nn"],
                "ratios": [1, 1, 1],
                "E_th_phase": 22.0518,
            },
        },
    },
    "7Li": {
        "Atom_mass": 7,
        "Z": 3,
        "N": 4,
        "Mass_MeV": 6535.366,
        "Mass_amu": 7.016004548,
        "E_binding": 14.9071052,
        "Energy_lvl": {
            "0": {
                "E_x": 0,
                "E_x_err_kev": 0,
                "J": 1.5,
                "pi": -1,
                "T": 0.5,
                "G": 0,
                "G_err": 0,
            },
            "1": {
                "E_x": 0.477612,
                "E_x_err_kev": 0.003,
                "J": 0.5,
                "pi": -1,
                "T": 0.5,
                "G": 0,
                "G_err": 0,
            },
            "2": {
                "E_x": 4.652,
                "E_x_err_kev": None,
                "J": 3.5,
                "pi": -1,
                "T": 0.5,
                "G": 0.069,
                "G_err": None,
            },
            "3": {
                "E_x": 6.604,
                "E_x_err_kev": None,
                "J": 2.5,
                "pi": -1,
                "T": 0.5,
                "G": 0.918,
                "G_err": None,
            },
            "4": {
                "E_x": 7.454,
                "E_x_err_kev": None,
                "J": 2.5,
                "pi": -1,
                "T": 0.5,
                "G": 0.08,
                "G_err": None,
            },
            "5": {
                "E_x": 8.75,
                "E_x_err_kev": None,
                "J": 1.5,
                "pi": -1,
                "T": 0.5,
                "G": 4.712,
                "G_err": None,
            },
            "6": {
                "E_x": 9.09,
                "E_x_err_kev": None,
                "J": 0.5,
                "pi": -1,
                "T": 0.5,
                "G": 2.752,
                "G_err": None,
            },
            "7": {
                "E_x": 9.57,
                "E_x_err_kev": None,
                "J": 3.5,
                "pi": -1,
                "T": 0.5,
                "G": 0.437,
                "G_err": None,
            },
            "8": {
                "E_x": 11.24,
                "E_x_err_kev": 30,
                "J": 1.5,
                "pi": -1,
                "T": 0.5,
                "G": 0.26,
                "G_err": 0.035,
            },
            "9": {
                "E_x": 13.7,
                "E_x_err_kev": None,
                "J": None,
                "pi": None,
                "T": None,
                "G": 0.5,
                "G_err": None,
            },
            "10": {
                "E_x": 14.7,
                "E_x_err_kev": None,
                "J": None,
                "pi": None,
                "T": None,
                "G": 0.7,
                "G_err": None,
            },
        },
        "Phase_volume": {
            "0": {
                "phase_particles": ["4He", "3H"],
                "ratios": [1, 1],
                "E_th_phase": 2.467,
            },
            "1": {
                "phase_particles": ["6Li", "nn"],
                "ratios": [1, 1],
                "E_th_phase": 7.2499,
            },
            "2": {
                "phase_particles": ["5He", "2H"],
                "ratios": [1, 1],
                "E_th_phase": 9.522,
            },
            "3": {
                "phase_particles": ["6He", "1H"],
                "ratios": [1, 1],
                "E_th_phase": 9.9754,
            },
            "4": {
                "phase_particles": ["5Li", "nn"],
                "ratios": [1, 2],
                "E_th_phase": 12.64,
            },
        },
    },
    "8Li": {
        "Atom_mass": 8,
        "Z": 3,
        "N": 5,
        "Mass_MeV": 7491.69684304,
        "Mass_amu": 8.02248624,
        "E_binding": 20.945804,
        "Energy_lvl": {
            "0": {
                "E_x": 0,
                "E_x_err_kev": 0,
                "J": 2,
                "pi": 1,
                "T": 1,
                "G": 0,
                "G_err": 0,
            },
            "1": {
                "E_x": 0.9808,
                "E_x_err_kev": 0.1,
                "J": 1,
                "pi": 1,
                "T": 1,
                "G": 0,
                "G_err": 0,
            },
            "2": {
                "E_x": 2.255,
                "E_x_err_kev": None,
                "J": 3,
                "pi": 1,
                "T": 1,
                "G": 0,
                "G_err": 0,
            },
            "3": {
                "E_x": 3.21,
                "E_x_err_kev": None,
                "J": 1,
                "pi": 1,
                "T": 1,
                "G": 1,
                "G_err": 0,
            },
            "4": {
                "E_x": 5.4,
                "E_x_err_kev": None,
                "J": 1,
                "pi": 1,
                "T": 1,
                "G": 0.65,
                "G_err": None,
            },
            "5": {
                "E_x": 6.1,
                "E_x_err_kev": 100,
                "J": 3,
                "pi": None,
                "T": 1,
                "G": 1,
                "G_err": None,
            },
            "6": {
                "E_x": 6.53,
                "E_x_err_kev": 20,
                "J": 4,
                "pi": 1,
                "T": 1,
                "G": 0.035,
                "G_err": None,
            },
            "7": {
                "E_x": 7.1,
                "E_x_err_kev": 100,
                "J": None,
                "pi": None,
                "T": None,
                "G": 0.4,
                "G_err": None,
            },
            "8": {
                "E_x": 9,
                "E_x_err_kev": None,
                "J": None,
                "pi": None,
                "T": None,
                "G": 6,
                "G_err": None,
            },
            "9": {
                "E_x": 9.67,
                "E_x_err_kev": None,
                "J": 1,
                "pi": 1,
                "T": None,
                "G": 1,
                "G_err": None,
            },
            "10": {
                "E_x": 10.8222,
                "E_x_err_kev": 5.5,
                "J": 0,
                "pi": 1,
                "T": 2,
                "G": 0.012,
                "G_err": None,
            },
        },
        "Phase_volume": {
            "0": {
                "phase_particles": ["7Li", "nn"],
                "ratios": [1, 1],
                "E_th_phase": 2.03229,
            },
            "1": {
                "phase_particles": ["4He", "3H", "nn"],
                "ratios": [1, 1, 1],
                "E_th_phase": 4.49920,
            },
            "2": {
                "phase_particles": ["5He", "3H"],
                "ratios": [1, 1],
                "E_th_phase": 5.393,
            },
            "3": {
                "phase_particles": ["6He", "2H"],
                "ratios": [1, 1],
                "E_th_phase": 9.7840,
            },
        },
    },
    "9Li": {
        "Atom_mass": 9,
        "Z": 3,
        "N": 6,
        "Mass_MeV": 8427.25307542,
        "Mass_amu": 9.02679019,
        "E_binding": 24.954902,
        "Energy_lvl": {
            "0": {
                "E_x": 0,
                "E_x_err_kev": 0,
                "J": 1.5,
                "pi": -1,
                "T": 1.5,
                "G": 0,
                "G_err": 0,
            },
            "1": {
                "E_x": 2.691,
                "E_x_err_kev": 5,
                "J": 0.5,
                "pi": -1,
                "T": None,
                "G": None,
                "G_err": None,
            },
            "2": {
                "E_x": 4.296,
                "E_x_err_kev": 15,
                "J": 2.5,
                "pi": -1,
                "T": None,
                "G": 0.1,
                "G_err": 0.03,
            },
            "3": {
                "E_x": 5.38,
                "E_x_err_kev": 60,
                "J": None,
                "pi": None,
                "T": None,
                "G": 0.6,
                "G_err": 0.1,
            },
            "4": {
                "E_x": 6.43,
                "E_x_err_kev": 15,
                "J": None,
                "pi": None,
                "T": None,
                "G": 0.04,
                "G_err": 0.02,
            },
        },
        "Phase_volume": {
            "0": {
                "phase_particles": ["8Li", "nn"],
                "ratios": [1, 1],
                "E_th_phase": 4.0639,
            },
            "1": {
                "phase_particles": ["7Li", "nn"],
                "ratios": [1, 2],
                "E_th_phase": 6.0962,
            },
            "2": {
                "phase_particles": ["6He", "3H"],
                "ratios": [1, 1],
                "E_th_phase": 7.5906,
            },
        },
    },
    "10Li": {
        "Atom_mass": 10,
        "Z": 3,
        "N": 1,
        "Mass_MeV": 3721.3287015200003,
        "Mass_amu": 10.035483,
        "E_binding": 33.052624,
        "Energy_lvl": {
            "0": {"E_x": 0, "J": 0.5, "pi": 1, "T": None},
            "1": {"E_x": 15, "J": None, "pi": None, "T": None},
            "2": {"E_x": 20, "J": None, "pi": None, "T": None},
        },
        "Phase_volume": {"0": None},
    },
    "5Be": {
        "Atom_mass": 5,
        "Z": 4,
        "N": 1,
        "Mass_MeV": 4655.5143239,
        "Mass_amu": 5.03987,
        "E_binding": 37.139,
        "Energy_lvl": {
            "0": {
                "E_x": 0,
                "E_x_err_kev": 0,
                "J": None,
                "pi": None,
                "T": None,
                "G": None,
                "G_err": None,
            },
        },
        "Phase_volume": {
            "0": {
                "phase_particles": ["3He", "1H"],
                "ratios": [1, 2],
                "E_th_phase": -4.2,
            }
        },
    },
    "6Be": {
        "Atom_mass": 6,
        "Z": 4,
        "N": 2,
        "Mass_MeV": 5613.84362028,
        "Mass_amu": 6.019726,
        "E_binding": 18.375034,
        "Energy_lvl": {
            "0": {
                "E_x": 0,
                "E_x_err_kev": 0,
                "J": 0,
                "pi": 1,
                "T": 1,
                "G": 0.092,
                "G_err": 0.006,
            },
            "1": {
                "E_x": 1.67,
                "E_x_err_kev": 50,
                "J": 2,
                "pi": 1,
                "T": 1,
                "G": 1.16,
                "G_err": 0.06,
            },
            "2": {
                "E_x": 23,
                "E_x_err_kev": 0,
                "J": 4,
                "pi": -1,
                "T": None,
                "G": None,
                "G_err": None,
            },
            "3": {
                "E_x": 26,
                "E_x_err_kev": 0,
                "J": 2,
                "pi": -1,
                "T": None,
                "G": None,
                "G_err": None,
            },
            "4": {
                "E_x": 27,
                "E_x_err_kev": 0,
                "J": 3,
                "pi": -1,
                "T": None,
                "G": None,
                "G_err": None,
            },
        },
        "Phase_volume": {
            "0": {
                "phase_particles": ["4He", "1H"],
                "ratios": [1, 2],
                "E_th_phase": -1.3711,
            },
            "1": {
                "phase_particles": ["5Li", "1H"],
                "ratios": [1, 1],
                "E_th_phase": 0.32,
            },
            "2": {
                "phase_particles": ["3He", "3He"],
                "ratios": [1, 1],
                "E_th_phase": 11.4884,
            },
        },
    },
    "7Be": {
        "Atom_mass": 7,
        "Z": 4,
        "N": 3,
        "Mass_MeV": 6556.01498566,
        "Mass_amu": 7.01692871,
        "E_binding": 15.768999,
        "Energy_lvl": {
            "0": {
                "E_x": 0,
                "E_x_err_kev": 0,
                "J": 1.5,
                "pi": -1,
                "T": 0.5,
                "G": 0,
                "G_err": 0,
            },
            "1": {
                "E_x": 0.42908,
                "E_x_err_kev": 0.10,
                "J": 0.5,
                "pi": -1,
                "T": 0.5,
                "G": 0,
                "G_err": 0,
            },
            "2": {
                "E_x": 4.57,
                "E_x_err_kev": 50,
                "J": 3.5,
                "pi": -1,
                "T": 0.5,
                "G": 0.175,
                "G_err": 0.007,
            },
            "3": {
                "E_x": 6.73,
                "E_x_err_kev": 100,
                "J": 2.5,
                "pi": -1,
                "T": 0.5,
                "G": 1.2,
                "G_err": None,
            },
            "4": {
                "E_x": 7.21,
                "E_x_err_kev": 60,
                "J": 2.5,
                "pi": -1,
                "T": 0.5,
                "G": 0,
                "G_err": 0,
            },
            "5": {
                "E_x": 9.27,
                "E_x_err_kev": 100,
                "J": 3.5,
                "pi": -1,
                "T": 0.5,
                "G": None,
                "G_err": None,
            },
            "6": {
                "E_x": 9.9,
                "E_x_err_kev": None,
                "J": 1.5,
                "pi": -1,
                "T": 0.5,
                "G": 1.8,
                "G_err": None,
            },
            "7": {
                "E_x": 11.01,
                "E_x_err_kev": 30,
                "J": 1.5,
                "pi": -1,
                "T": 0.5,
                "G": 0.32,
                "G_err": 0.03,
            },
            "8": {
                "E_x": 17,
                "E_x_err_kev": None,
                "J": 0.5,
                "pi": -1,
                "T": 1,
                "G": 6.5,
                "G_err": None,
            },
        },
        "Phase_volume": {
            "0": {
                "phase_particles": ["3He", "4He"],
                "ratios": [1, 1],
                "E_th_phase": 1.5866,
            },
            "1": {
                "phase_particles": ["6Li", "1H"],
                "ratios": [1, 1],
                "E_th_phase": 5.6058,
            },
            "2": {
                "phase_particles": ["5Li", "2H"],
                "ratios": [1, 1],
                "E_th_phase": 8.77,
            },
            "3": {
                "phase_particles": ["6Be", "nn"],
                "ratios": [1, 1],
                "E_th_phase": 10.6758,
            },
        },
    },
    "8Be": {
        "Atom_mass": 8,
        "Z": 4,
        "N": 4,
        "Mass_MeV": 7506.40764404,
        "Mass_amu": 8.00530510,
        "E_binding": 4.941671,
        "Energy_lvl": {
            "0": {
                "E_x": 0,
                "E_x_err_kev": 0,
                "J": 0,
                "pi": 1,
                "T": 0,
                "G": 0.00557,
                "G_err": 0.0000025,
            },
            "1": {
                "E_x": 3.03,
                "E_x_err_kev": 10,
                "J": 2,
                "pi": 1,
                "T": 0,
                "G": 1.513,
                "G_err": 0.015,
            },
            "2": {
                "E_x": 11.35,
                "E_x_err_kev": 150,
                "J": 4,
                "pi": 1,
                "T": 0,
                "G": 3.5,
                "G_err": None,
            },
            "3": {
                "E_x": 16.626,
                "E_x_err_kev": 3,
                "J": 2,
                "pi": 1,
                "T": [0, 1],
                "G": 0.108,
                "G_err": 0.0005,
            },
            "4": {
                "E_x": 16.922,
                "E_x_err_kev": 3,
                "J": 2,
                "pi": 1,
                "T": [0, 1],
                "G": 0.074,
                "G_err": 0.0004,
            },
            "5": {
                "E_x": 17.640,
                "E_x_err_kev": 1,
                "J": 1,
                "pi": 1,
                "T": 1,
                "G": 0.0107,
                "G_err": 0.0005,
            },
            "6": {
                "E_x": 18.150,
                "E_x_err_kev": 4,
                "J": 1,
                "pi": 1,
                "T": 0,
                "G": 0.138,
                "G_err": 0.006,
            },
            "7": {
                "E_x": 18.91,
                "E_x_err_kev": None,
                "J": 2,
                "pi": -1,
                "T": [0, 1],
                "G": 0.122,
                "G_err": None,
            },
            "8": {
                "E_x": 19.07,
                "E_x_err_kev": 30,
                "J": 3,
                "pi": 1,
                "T": 1,
                "G": 0.27,
                "G_err": 0.02,
            },
            "9": {
                "E_x": 19.235,
                "E_x_err_kev": 10,
                "J": 3,
                "pi": 1,
                "T": 0,
                "G": 0.227,
                "G_err": 0.016,
            },
            "10": {
                "E_x": 19.4,
                "E_x_err_kev": None,
                "J": 1,
                "pi": -1,
                "T": None,
                "G": 0,
                "G_err": 0,
            },
            "11": {
                "E_x": 19.86,
                "E_x_err_kev": 50,
                "J": 4,
                "pi": 1,
                "T": 0,
                "G": 0.645,
                "G_err": None,
            },
            "12": {
                "E_x": 20.1,
                "E_x_err_kev": None,
                "J": 2,
                "pi": 1,
                "T": 0,
                "G": 0.88,
                "G_err": 0.02,
            },
            "13": {
                "E_x": 20.2,
                "E_x_err_kev": None,
                "J": 0,
                "pi": 1,
                "T": 0,
                "G": 0.72,
                "G_err": 0.02,
            },
            "14": {
                "E_x": 20.9,
                "E_x_err_kev": None,
                "J": 4,
                "pi": -1,
                "T": None,
                "G": 1.6,
                "G_err": 0.2,
            },
            "15": {
                "E_x": 21.5,
                "E_x_err_kev": None,
                "J": 3,
                "pi": 1,
                "T": None,
                "G": 1,
                "G_err": None,
            },
            "16": {
                "E_x": 22.0,
                "E_x_err_kev": None,
                "J": 1,
                "pi": -1,
                "T": 1,
                "G": 4,
                "G_err": None,
            },
            "17": {
                "E_x": 22.05,
                "E_x_err_kev": 100,
                "J": None,
                "pi": None,
                "T": None,
                "G": 0.27,
                "G_err": 0.07,
            },
            "18": {
                "E_x": 22.2,
                "E_x_err_kev": None,
                "J": 2,
                "pi": 1,
                "T": 0,
                "G": 0.8,
                "G_err": None,
            },
            "19": {
                "E_x": 22.63,
                "E_x_err_kev": 100,
                "J": None,
                "pi": None,
                "T": None,
                "G": 0.1,
                "G_err": 0.05,
            },
            "20": {
                "E_x": 22.98,
                "E_x_err_kev": 100,
                "J": None,
                "pi": None,
                "T": None,
                "G": 0.23,
                "G_err": 0.05,
            },
            "21": {
                "E_x": 24.0,
                "E_x_err_kev": None,
                "J": [1, 2],
                "pi": -1,
                "T": 1,
                "G": 7,
                "G_err": None,
            },
            "22": {
                "E_x": 25.2,
                "E_x_err_kev": None,
                "J": 2,
                "pi": 1,
                "T": 0,
                "G": None,
                "G_err": None,
            },
            "23": {
                "E_x": 25.5,
                "E_x_err_kev": None,
                "J": 4,
                "pi": 1,
                "T": 0,
                "G": 0,
                "G_err": None,
            },
            "24": {
                "E_x": 27.4941,
                "E_x_err_kev": 1.8,
                "J": 0,
                "pi": 1,
                "T": 2,
                "G": 0.0055,
                "G_err": 0.002,
            },
            "25": {
                "E_x": 28.6,
                "E_x_err_kev": None,
                "J": None,
                "pi": None,
                "T": None,
                "G": 0,
                "G_err": None,
            },
            "26": {
                "E_x": 32,
                "E_x_err_kev": None,
                "J": None,
                "pi": None,
                "T": None,
                "G": 1,
                "G_err": None,
            },
            "27": {
                "E_x": 41,
                "E_x_err_kev": None,
                "J": None,
                "pi": None,
                "T": None,
                "G": None,
                "G_err": None,
            },
            "28": {
                "E_x": 43,
                "E_x_err_kev": None,
                "J": None,
                "pi": None,
                "T": None,
                "G": None,
                "G_err": None,
            },
            "29": {
                "E_x": 50,
                "E_x_err_kev": None,
                "J": None,
                "pi": None,
                "T": None,
                "G": None,
                "G_err": None,
            },
        },
        "Phase_volume": {
            "0": {
                "phase_particles": ["4He", "4He"],
                "ratios": [1, 1],
                "E_th_phase": -0.0918,
            },
            "1": {
                "phase_particles": ["7Li", "1H"],
                "ratios": [1, 1],
                "E_th_phase": 17.2551,
            },
            "2": {
                "phase_particles": ["7Be", "nn"],
                "ratios": [1, 1],
                "E_th_phase": 18.8997,
            },
            "3": {
                "phase_particles": ["5He", "3He"],
                "ratios": [1, 1],
                "E_th_phase": 21.38,
            },
            "4": {
                "phase_particles": ["6Li", "2H"],
                "ratios": [1, 1],
                "E_th_phase": 22.2808,
            },
        },
    },
    "9Be": {
        "Atom_mass": 9,
        "Z": 4,
        "N": 5,
        "Mass_MeV": 8439.56619242,
        "Mass_amu": 9.01218306,
        "E_binding": 11.348453,
        "Energy_lvl": {
            "0": {
                "E_x": 0,
                "E_x_err_kev": 0,
                "J": 1.5,
                "pi": -1,
                "T": 0.5,
                "G": 0,
                "G_err": 0,
            },
            "1": {
                "E_x": 1.684,
                "E_x_err_kev": 7,
                "J": 0.5,
                "pi": 1,
                "T": None,
                "G": 0.217,
                "G_err": 0.01,
            },
            "2": {
                "E_x": 2.4294,
                "E_x_err_kev": 1.3,
                "J": 2.5,
                "pi": -1,
                "T": None,
                "G": 0.00078,
                "G_err": 0.00013,
            },
            "3": {
                "E_x": 2.78,
                "E_x_err_kev": 120,
                "J": 0.5,
                "pi": -1,
                "T": None,
                "G": 1.08,
                "G_err": 0.11,
            },
            "4": {
                "E_x": 3.049,
                "E_x_err_kev": 9,
                "J": 2.5,
                "pi": 1,
                "T": None,
                "G": 0.282,
                "G_err": 0.011,
            },
            "5": {
                "E_x": 3.8,
                "E_x_err_kev": 0.1,
                "J": 1.5,
                "pi": -1,
                "T": None,
                "G": 1.2,
                "G_err": 0.2,
            },
            "6": {
                "E_x": 4.704,
                "E_x_err_kev": 25,
                "J": 1.5,
                "pi": 1,
                "T": None,
                "G": 0.743,
                "G_err": 0.055,
            },
            "7": {
                "E_x": 5.59,
                "E_x_err_kev": 100,
                "J": 1.5,
                "pi": -1,
                "T": None,
                "G": 1.330,
                "G_err": 0.360,
            },
            "8": {
                "E_x": 6.38,
                "E_x_err_kev": 60,
                "J": 3.5,
                "pi": -1,
                "T": None,
                "G": 1.210,
                "G_err": 0.230,
            },
            "9": {
                "E_x": 6.76,
                "E_x_err_kev": 60,
                "J": 4.5,
                "pi": 1,
                "T": None,
                "G": 1.330,
                "G_err": 0.090,
            },
            "10": {
                "E_x": 7.94,
                "E_x_err_kev": 80,
                "J": 2.5,
                "pi": -1,
                "T": None,
                "G": 1,
                "G_err": None,
            },
            "11": {
                "E_x": 11.283,
                "E_x_err_kev": 24,
                "J": 3.5,
                "pi": -1,
                "T": None,
                "G": 0.575,
                "G_err": 0.05,
            },
            "12": {
                "E_x": 11.81,
                "E_x_err_kev": 20,
                "J": 2.5,
                "pi": -1,
                "T": None,
                "G": 0.400,
                "G_err": 0.030,
            },
            "13": {
                "E_x": 13.79,
                "E_x_err_kev": 30,
                "J": None,
                "pi": -1,
                "T": None,
                "G": 0.590,
                "G_err": 0.06,
            },
            "14": {
                "E_x": 14.3922,
                "E_x_err_kev": 1.8,
                "J": 1.5,
                "pi": -1,
                "T": 1.5,
                "G": 0.000381,
                "G_err": 0.000033,
            },
            "15": {
                "E_x": 14.48,
                "E_x_err_kev": 90,
                "J": 2.5,
                "pi": -1,
                "T": 0.5,
                "G": 0.8,
                "G_err": None,
            },
            "16": {
                "E_x": 15.10,
                "E_x_err_kev": 50,
                "J": None,
                "pi": None,
                "T": None,
                "G": 0.350,
                "G_err": 0.180,
            },
            "17": {
                "E_x": 15.97,
                "E_x_err_kev": 30,
                "J": None,
                "pi": None,
                "T": 0.5,
                "G": 0.3,
                "G_err": None,
            },
            "18": {
                "E_x": 16.671,
                "E_x_err_kev": 8,
                "J": 2.5,
                "pi": 1,
                "T": 0.5,
                "G": 0.041,
                "G_err": 0.004,
            },
            "19": {
                "E_x": 16.9752,
                "E_x_err_kev": 0.8,
                "J": 0.5,
                "pi": -1,
                "T": 1.5,
                "G": 0.000389,
                "G_err": 0.00001,
            },
            "20": {
                "E_x": 17.298,
                "E_x_err_kev": 7,
                "J": 2.5,
                "pi": -1,
                "T": None,
                "G": 0.2,
                "G_err": None,
            },
            "21": {
                "E_x": 17.493,
                "E_x_err_kev": 7,
                "J": 3.5,
                "pi": 1,
                "T": 0.5,
                "G": 0.047,
                "G_err": None,
            },
            "22": {
                "E_x": 18.02,
                "E_x_err_kev": 50,
                "J": None,
                "pi": None,
                "T": None,
                "G": None,
                "G_err": None,
            },
            "23": {
                "E_x": 18.58,
                "E_x_err_kev": 40,
                "J": None,
                "pi": None,
                "T": None,
                "G": None,
                "G_err": None,
            },
            "24": {
                "E_x": 18.650,
                "E_x_err_kev": 50,
                "J": 2.5,
                "pi": -1,
                "T": 1.5,
                "G": 0.3,
                "G_err": 0.1,
            },
            "25": {
                "E_x": 19.20,
                "E_x_err_kev": 50,
                "J": None,
                "pi": None,
                "T": None,
                "G": 0.31,
                "G_err": 0.08,
            },
            "26": {
                "E_x": 19.420,
                "E_x_err_kev": 50,
                "J": None,
                "pi": None,
                "T": None,
                "G": 0.6,
                "G_err": 0.3,
            },
            "27": {
                "E_x": 19.9,
                "E_x_err_kev": 200,
                "J": None,
                "pi": None,
                "T": None,
                "G": None,
                "G_err": None,
            },
            "28": {
                "E_x": 20.51,
                "E_x_err_kev": 30,
                "J": None,
                "pi": None,
                "T": None,
                "G": 0.6,
                "G_err": 0.1,
            },
            "29": {
                "E_x": 20.75,
                "E_x_err_kev": 30,
                "J": None,
                "pi": None,
                "T": None,
                "G": 0.68,
                "G_err": 0.09,
            },
            "30": {
                "E_x": 21.4,
                "E_x_err_kev": 200,
                "J": None,
                "pi": None,
                "T": None,
                "G": None,
                "G_err": None,
            },
            "31": {
                "E_x": 22.4,
                "E_x_err_kev": 200,
                "J": None,
                "pi": None,
                "T": None,
                "G": 0,
                "G_err": None,
            },
            "32": {
                "E_x": 23.8,
                "E_x_err_kev": 200,
                "J": None,
                "pi": None,
                "T": None,
                "G": None,
                "G_err": None,
            },
            "33": {
                "E_x": 27.0,
                "E_x_err_kev": 500,
                "J": None,
                "pi": None,
                "T": None,
                "G": 0,
                "G_err": None,
            },
        },
        "Phase_volume": {
            "0": {
                "phase_particles": ["4He", "4He", "nn"],
                "ratios": [1, 1, 1],
                "E_th_phase": 1.5736,
            },
            "1": {
                "phase_particles": ["8Be", "nn"],
                "ratios": [1, 1],
                "E_th_phase": 1.6654,
            },
            "2": {
                "phase_particles": ["5He", "4He"],
                "ratios": [1, 1],
                "E_th_phase": 2.467,
            },
            "3": {
                "phase_particles": ["7Li", "2H"],
                "ratios": [1, 1],
                "E_th_phase": 16.6959,
            },
            "4": {
                "phase_particles": ["8Li", "1H"],
                "ratios": [1, 1],
                "E_th_phase": 16.8882,
            },
            "5": {
                "phase_particles": ["6Li", "3H"],
                "ratios": [1, 1],
                "E_th_phase": 17.6890,
            },
            "6": {
                "phase_particles": ["6He", "3He"],
                "ratios": [1, 1],
                "E_th_phase": 21.1787,
            },
        },
    },
    "10Be": {
        "Atom_mass": 10,
        "Z": 4,
        "N": 6,
        "Mass_MeV": 9377.872487800001,
        "Mass_amu": 10.01353469,
        "E_binding": 12.607488,
        "Energy_lvl": {
            "0": {"E_x": 0, "J": 0.5, "pi": 1, "T": None},
            "1": {"E_x": 15, "J": None, "pi": None, "T": None},
            "2": {"E_x": 20, "J": None, "pi": None, "T": None},
        },
        "Phase_volume": {"0": None},
    },
    "11Be": {
        "Atom_mass": 11,
        "Z": 4,
        "N": 7,
        "Mass_MeV": 10309.86813918,
        "Mass_amu": 11.02166108,
        "E_binding": 20.177167,
        "Energy_lvl": {
            "0": {"E_x": 0, "J": 0.5, "pi": 1, "T": None},
            "1": {"E_x": 15, "J": None, "pi": None, "T": None},
            "2": {"E_x": 20, "J": None, "pi": None, "T": None},
        },
        "Phase_volume": {"0": None},
    },
    "12Be": {
        "Atom_mass": 12,
        "Z": 4,
        "N": 8,
        "Mass_MeV": 11244.53287756,
        "Mass_amu": 12.0269221,
        "E_binding": 25.077759,
        "Energy_lvl": {
            "0": {"E_x": 0, "J": 0.5, "pi": 1, "T": None},
            "1": {"E_x": 15, "J": None, "pi": None, "T": None},
            "2": {"E_x": 20, "J": None, "pi": None, "T": None},
        },
        "Phase_volume": {"0": None},
    },
    "7B": {
        "Atom_mass": 7,
        "Z": 5,
        "N": 2,
        "Mass_MeV": 6542.81410266,
        "Mass_amu": 7.029712,
        "E_binding": 27.67655,
        "Energy_lvl": {
            "0": {
                "E_x": 0,
                "E_x_err_kev": 0,
                "J": None,
                "pi": None,
                "T": None,
                "G": 0,
                "G_err": 0,
            }
        },
        "Phase_volume": {
            "0": {
                "phase_particles": ["4He", "1H"],
                "ratios": [1, 3],
                "E_th_phase": -3.58,
            },
            "1": {
                "phase_particles": ["6Be", "1H"],
                "ratios": [1, 1],
                "E_th_phase": -2.21,
            },
        },
    },
    "8B": {
        "Atom_mass": 8,
        "Z": 5,
        "N": 3,
        "Mass_MeV": 7487.13440604,
        "Mass_amu": 8.0246073,
        "E_binding": 22.921577,
        "Energy_lvl": {
            "0": {
                "E_x": 0,
                "E_x_err_kev": 0,
                "J": 2,
                "pi": 1,
                "T": 2,
                "G": 0,
                "G_err": 0,
            },
            "1": {
                "E_x": 0.7695,
                "E_x_err_kev": 2.5,
                "J": 1,
                "pi": 1,
                "T": 1,
                "G": 0,
                "G_err": 0,
            },
            "2": {
                "E_x": 2.32,
                "E_x_err_kev": 20,
                "J": 3,
                "pi": 1,
                "T": 1,
                "G": 0.35,
                "G_err": 0.03,
            },
            "3": {
                "E_x": 3.5,
                "E_x_err_kev": 500,
                "J": 2,
                "pi": -1,
                "T": None,
                "G": 8,
                "G_err": 4,
            },
            "4": {
                "E_x": 10.619,
                "E_x_err_kev": 9,
                "J": 0,
                "pi": 1,
                "T": 2,
                "G": 0.06,
                "G_err": None,
            },
        },
        "Phase_volume": {
            "0": {
                "phase_particles": ["7Be", "1H"],
                "ratios": [1, 1],
                "E_th_phase": 0.1375,
            },
            "1": {
                "phase_particles": ["4He", "3He", "1H"],
                "ratios": [1, 1, 1],
                "E_th_phase": 1.7236,
            },
            "2": {
                "phase_particles": ["5Li", "3He"],
                "ratios": [1, 1],
                "E_th_phase": 3.69,
            },
            "3": {
                "phase_particles": ["6Be", "2H"],
                "ratios": [1, 1],
                "E_th_phase": 8.589,
            },
        },
    },
    "9B": {
        "Atom_mass": 9,
        "Z": 5,
        "N": 4,
        "Mass_MeV": 8437.20482542,
        "Mass_amu": 9.0133296,
        "E_binding": 12.416488,
        "Energy_lvl": {
            "0": {
                "E_x": 0,
                "E_x_err_kev": 0,
                "J": 1.5,
                "pi": -1,
                "T": 0.5,
                "G": 0.00054,
                "G_err": 0.00021,
            },
            "1": {
                "E_x": 1.6,
                "E_x_err_kev": None,
                "J": None,
                "pi": None,
                "T": None,
                "G": None,
                "G_err": None,
            },
            "2": {
                "E_x": 2.361,
                "E_x_err_kev": 5,
                "J": 2.5,
                "pi": -1,
                "T": 0.5,
                "G": 0.081,
                "G_err": 0.005,
            },
            "3": {
                "E_x": 2.75,
                "E_x_err_kev": 300,
                "J": 0.5,
                "pi": -1,
                "T": 0.5,
                "G": 3.13,
                "G_err": 0.2,
            },
            "4": {
                "E_x": 2.788,
                "E_x_err_kev": 30,
                "J": 2.5,
                "pi": 1,
                "T": 0.5,
                "G": 0.55,
                "G_err": 0.04,
            },
            "5": {
                "E_x": 4.3,
                "E_x_err_kev": 200,
                "J": None,
                "pi": None,
                "T": None,
                "G": 1.6,
                "G_err": 0.2,
            },
            "6": {
                "E_x": 6.97,
                "E_x_err_kev": 60,
                "J": 3.5,
                "pi": -1,
                "T": 0.5,
                "G": 2,
                "G_err": 0.2,
            },
            "7": {
                "E_x": 11.65,
                "E_x_err_kev": 60,
                "J": 3.5,
                "pi": -1,
                "T": 0.5,
                "G": 0.8,
                "G_err": 0.05,
            },
            "8": {
                "E_x": 12.19,
                "E_x_err_kev": 40,
                "J": 2.5,
                "pi": -1,
                "T": 0.5,
                "G": 0.45,
                "G_err": 0.02,
            },
            "9": {
                "E_x": 14.01,
                "E_x_err_kev": 70,
                "J": None,
                "pi": -1,
                "T": 0.5,
                "G": 0.39,
                "G_err": 0.11,
            },
            "10": {
                "E_x": 14.6550,
                "E_x_err_kev": 2.5,
                "J": 1.5,
                "pi": -1,
                "T": 0.5,
                "G": 0.000395,
                "G_err": 0.000042,
            },
            "11": {
                "E_x": 14.7,
                "E_x_err_kev": 200,
                "J": 2.5,
                "pi": -1,
                "T": 0.5,
                "G": 1.35,
                "G_err": 0.2,
            },
            "12": {
                "E_x": 15.29,
                "E_x_err_kev": 40,
                "J": None,
                "pi": None,
                "T": 0.5,
                "G": None,
                "G_err": None,
            },
            "13": {
                "E_x": 15.58,
                "E_x_err_kev": 40,
                "J": None,
                "pi": None,
                "T": 0.5,
                "G": None,
                "G_err": None,
            },
            "14": {
                "E_x": 16.024,
                "E_x_err_kev": 25,
                "J": None,
                "pi": None,
                "T": 0.5,
                "G": 0.18,
                "G_err": 0.016,
            },
            "15": {
                "E_x": 16.71,
                "E_x_err_kev": 100,
                "J": 2.5,
                "pi": 1,
                "T": 0.5,
                "G": None,
                "G_err": None,
            },
            "16": {
                "E_x": 17.076,
                "E_x_err_kev": 4,
                "J": 0.5,
                "pi": -1,
                "T": 1.5,
                "G": 0.022,
                "G_err": 0.005,
            },
            "17": {
                "E_x": 17.190,
                "E_x_err_kev": 25,
                "J": None,
                "pi": None,
                "T": None,
                "G": 0.12,
                "G_err": 0.04,
            },
            "18": {
                "E_x": 17.54,
                "E_x_err_kev": 100,
                "J": 3.5,
                "pi": 1,
                "T": 0.5,
                "G": None,
                "G_err": None,
            },
            "19": {
                "E_x": 17.637,
                "E_x_err_kev": 10,
                "J": None,
                "pi": None,
                "T": None,
                "G": 0.071,
                "G_err": 0.008,
            },
        },
        "Phase_volume": {
            "0": {
                "phase_particles": ["8Be", "1H"],
                "ratios": [1, 1],
                "E_th_phase": -0.1851,
            },
            "1": {
                "phase_particles": ["5Li", "4He"],
                "ratios": [1, 1],
                "E_th_phase": 1.689,
            },
            "2": {
                "phase_particles": ["7Be", "2H"],
                "ratios": [1, 1],
                "E_th_phase": 16.4901,
            },
            "3": {
                "phase_particles": ["6Li", "3He"],
                "ratios": [1, 1],
                "E_th_phase": 16.6023,
            },
            "4": {
                "phase_particles": ["8B", "nn"],
                "ratios": [1, 1],
                "E_th_phase": 18.5771,
            },
            "5": {
                "phase_particles": ["6Be", "3H"],
                "ratios": [1, 1],
                "E_th_phase": 20.909,
            },
        },
    },
    "10B": {
        "Atom_mass": 10,
        "Z": 5,
        "N": 5,
        "Mass_MeV": 9377.1359538,
        "Mass_amu": 10.012936992,
        "E_binding": 12.05069,
        "Energy_lvl": {
            "0": {"E_x": 0, "J": 0.5, "pi": 1, "T": None},
            "1": {"E_x": 15, "J": None, "pi": None, "T": None},
            "2": {"E_x": 20, "J": None, "pi": None, "T": None},
        },
        "Phase_volume": {"0": None},
    },
    "11B": {
        "Atom_mass": 11,
        "Z": 5,
        "N": 6,
        "Mass_MeV": 10255.102,
        "Mass_amu": 11.009305167,
        "E_binding": 8.667883,
        "Energy_lvl": {
            "0": {"E_x": 0, "J": 0.5, "pi": 1, "T": None},
            "1": {"E_x": 15, "J": None, "pi": None, "T": None},
            "2": {"E_x": 20, "J": None, "pi": None, "T": None},
        },
        "Phase_volume": {"0": None},
    },
    "12B": {
        "Atom_mass": 12,
        "Z": 5,
        "N": 7,
        "Mass_MeV": 11254.94788856,
        "Mass_amu": 12.0143526,
        "E_binding": 13.369416,
        "Energy_lvl": {
            "0": {"E_x": 0, "J": 0.5, "pi": 1, "T": None},
            "1": {"E_x": 15, "J": None, "pi": None, "T": None},
            "2": {"E_x": 20, "J": None, "pi": None, "T": None},
        },
        "Phase_volume": {"0": None},
    },
    "8C": {
        "Atom_mass": 8,
        "Z": 6,
        "N": 2,
        "Mass_MeV": 7473.69838204,
        "Mass_amu": 8.037643,
        "E_binding": 35.064269,
        "Energy_lvl": {
            "0": {
                "E_x": 0,
                "E_x_err_kev": 0,
                "J": 0,
                "pi": 1,
                "T": 2,
                "G": 0,
                "G_err": 0,
            },
        },
        "Phase_volume": {
            "0": {
                "phase_particles": ["6Be", "1H"],
                "ratios": [1, 2],
                "E_th_phase": -2.141,
            },
            "1": {
                "phase_particles": ["7B", "1H"],
                "ratios": [1, 1],
                "E_th_phase": 0.065,
            },
        },
    },
    "9C": {
        "Atom_mass": 9,
        "Z": 6,
        "N": 3,
        "Mass_MeV": 8419.417011419999,
        "Mass_amu": 9.0310372,
        "E_binding": 28.91097,
        "Energy_lvl": {
            "0": {
                "E_x": 0,
                "E_x_err_kev": 0,
                "J": 1.5,
                "pi": -1,
                "T": 1.5,
                "G": 0,
                "G_err": 0,
            },
            "1": {
                "E_x": 2.218,
                "E_x_err_kev": 11,
                "J": 0.5,
                "pi": -1,
                "T": None,
                "G": 0.1,
                "G_err": 0.02,
            },
        },
        "Phase_volume": {
            "0": {"phase_particles": ["8B", "1H"], "ratios": [1, 1], "E_th_phase": 1.3},
            "1": {
                "phase_particles": ["7Be", "1H"],
                "ratios": [1, 2],
                "E_th_phase": 1.4375,
            },
            "2": {
                "phase_particles": ["6Be", "3He"],
                "ratios": [1, 1],
                "E_th_phase": 4.3957,
            },
        },
    },
    "10C": {
        "Atom_mass": 10,
        "Z": 6,
        "N": 4,
        "Mass_MeV": 9372.194556800001,
        "Mass_amu": 10.01685322,
        "E_binding": 15.698755,
        "Energy_lvl": {
            "0": {"E_x": 0, "J": 0.5, "pi": 1, "T": None},
            "1": {"E_x": 15, "J": None, "pi": None, "T": None},
            "2": {"E_x": 20, "J": None, "pi": None, "T": None},
        },
        "Phase_volume": {"0": None},
    },
    "11C": {
        "Atom_mass": 11,
        "Z": 6,
        "N": 5,
        "Mass_MeV": 10254.018,
        "Mass_amu": 11.011433613,
        "E_binding": 10.650295,
        "Energy_lvl": {
            "0": {"E_x": 0, "J": 0.5, "pi": 1, "T": None},
            "1": {"E_x": 2, "J": None, "pi": None, "T": None},
            "2": {"E_x": 4.3188, "J": None, "pi": None, "T": None},
            "3": {"E_x": 4.8042, "J": None, "pi": None, "T": None},
            "4": {"E_x": 6.3392, "J": None, "pi": None, "T": None},
            "5": {"E_x": 6.4782, "J": None, "pi": None, "T": None},
            "6": {"E_x": 6.9048, "J": None, "pi": None, "T": None},
            "7": {"E_x": 7.4, "J": None, "pi": None, "T": None},
            "8": {"E_x": 7.4997, "J": None, "pi": None, "T": None},
            "9": {"E_x": 8.1045, "J": None, "pi": None, "T": None},
            "10": {"E_x": 8.420, "J": None, "pi": None, "T": None},
            # "11": {"E_x": 8.654, "J": None, "pi": None, "T": None},
            # "12": {"E_x": 8.699, "J": None, "pi": None, "T": None},
            # "13": {"E_x": 9.20, "J": None, "pi": None, "T": None},
            # "14": {"E_x": 9.645, "J": None, "pi": None, "T": None},
            # "15": {"E_x": 9.780, "J": None, "pi": None, "T": None},
            # "16": {"E_x": 9.970, "J": None, "pi": None, "T": None},
            # "17": {"E_x": 10.083, "J": None, "pi": None, "T": None},
        },
        "Phase_volume": {"0": None},
    },
    "12C": {
        "Atom_mass": 12,
        "Z": 6,
        "N": 6,
        "Mass_MeV": 11174.862,
        "Mass_amu": 12.000,
        "E_binding": 0,
        "Energy_lvl": {
            "0": {"E_x": 0, "J": 0.5, "pi": 1, "T": None},
            "1": {"E_x": 4.4398, "J": None, "pi": None, "T": None},
            "2": {"E_x": 7.654, "J": None, "pi": None, "T": None},
            "3": {"E_x": 9.641, "J": None, "pi": None, "T": None},
            "4": {"E_x": 9.87, "J": None, "pi": None, "T": None},
        },
        "Phase_volume": {"0": None},
    },
    "13C": {
        "Atom_mass": 13,
        "Z": 6,
        "N": 7,
        "Mass_MeV": 12203.46429419,
        "Mass_amu": 13.003354835336,
        "E_binding": 3.12500875,
        "Energy_lvl": {
            "0": {"E_x": 0, "J": 0.5, "pi": 1, "T": None},
            "1": {"E_x": 15, "J": None, "pi": None, "T": None},
            "2": {"E_x": 20, "J": None, "pi": None, "T": None},
        },
        "Phase_volume": {"0": None},
    },
    "14C": {
        "Atom_mass": 14,
        "Z": 6,
        "N": 8,
        "Mass_MeV": 13143.134740540001,
        "Mass_amu": 14.003241989,
        "E_binding": 3.01989278,
        "Energy_lvl": {
            "0": {"E_x": 0, "J": 0.5, "pi": 1, "T": None},
            "1": {"E_x": 15, "J": None, "pi": None, "T": None},
            "2": {"E_x": 20, "J": None, "pi": None, "T": None},
        },
        "Phase_volume": {"0": None},
    },
    "15C": {
        "Atom_mass": 15,
        "Z": 6,
        "N": 9,
        "Mass_MeV": 14075.8468197,
        "Mass_amu": 15.0105993,
        "E_binding": 9.873144,
        "Energy_lvl": {
            "0": {"E_x": 0, "J": 0.5, "pi": 1, "T": None},
            "1": {"E_x": 15, "J": None, "pi": None, "T": None},
            "2": {"E_x": 20, "J": None, "pi": None, "T": None},
        },
        "Phase_volume": {"0": None},
    },
    "16C": {
        "Atom_mass": 16,
        "Z": 6,
        "N": 10,
        "Mass_MeV": 15011.591166080001,
        "Mass_amu": 16.014701,
        "E_binding": 13.694128,
        "Energy_lvl": {
            "0": {"E_x": 0, "J": 0.5, "pi": 1, "T": None},
            "1": {"E_x": 15, "J": None, "pi": None, "T": None},
            "2": {"E_x": 20, "J": None, "pi": None, "T": None},
        },
        "Phase_volume": {"0": None},
    },
    "10N": {
        "Atom_mass": 16,
        "Z": 7,
        "N": 3,
        "Mass_MeV": 9347.799979800002,
        "Mass_amu": 10.04165,
        "E_binding": 38.800,
        "Energy_lvl": {
            "0": {"E_x": 0, "J": 0.5, "pi": 1, "T": None},
            "1": {"E_x": 15, "J": None, "pi": None, "T": None},
            "2": {"E_x": 20, "J": None, "pi": None, "T": None},
        },
        "Phase_volume": {"0": None},
    },
    "11N": {
        "Atom_mass": 16,
        "Z": 7,
        "N": 4,
        "Mass_MeV": 10301.79931018,
        "Mass_amu": 11.026158,
        "E_binding": 24.366,
        "Energy_lvl": {
            "0": {"E_x": 0, "J": 0.5, "pi": 1, "T": None},
            "1": {"E_x": 15, "J": None, "pi": None, "T": None},
            "2": {"E_x": 20, "J": None, "pi": None, "T": None},
        },
        "Phase_volume": {"0": None},
    },
    "12N": {
        "Atom_mass": 16,
        "Z": 7,
        "N": 5,
        "Mass_MeV": 11248.39264056,
        "Mass_amu": 12.0186132,
        "E_binding": 17.338,
        "Energy_lvl": {
            "0": {"E_x": 0, "J": 0.5, "pi": 1, "T": None},
            "1": {"E_x": 15, "J": None, "pi": None, "T": None},
            "2": {"E_x": 20, "J": None, "pi": None, "T": None},
        },
        "Phase_volume": {"0": None},
    },
    "13N": {
        "Atom_mass": 16,
        "Z": 7,
        "N": 6,
        "Mass_MeV": 12199.95097094,
        "Mass_amu": 13.005738609,
        "E_binding": 5.345,
        "Energy_lvl": {
            "0": {"E_x": 0, "J": 0.5, "pi": 1, "T": None},
            "1": {"E_x": 2.365, "J": None, "pi": None, "T": None},
            "2": {"E_x": 3.50, "J": None, "pi": None, "T": None},
            "3": {"E_x": 3.55, "J": None, "pi": None, "T": None},
            "4": {"E_x": 6.36, "J": None, "pi": None, "T": None},
            "5": {"E_x": 6.89, "J": None, "pi": None, "T": None},
            "6": {"E_x": 7.16, "J": None, "pi": None, "T": None},
            "7": {"E_x": 7.38, "J": None, "pi": None, "T": None},
            "8": {"E_x": 7.9, "J": None, "pi": None, "T": None},
            "9": {"E_x": 8.92, "J": None, "pi": None, "T": None},
            "10": {"E_x": 9.0, "J": None, "pi": None, "T": None},
            "11": {"E_x": 9.48, "J": None, "pi": None, "T": None},
        },
        "Phase_volume": {"0": None},
    },
    "14N": {
        "Atom_mass": 16,
        "Z": 7,
        "N": 7,
        "Mass_MeV": 13141.998301320002,
        "Mass_amu": 14.003074004251,
        "E_binding": 2.863,
        "Energy_lvl": {
            "0": {"E_x": 0, "J": 0.5, "pi": 1, "T": None},
            "1": {"E_x": 15, "J": None, "pi": None, "T": None},
            "2": {"E_x": 20, "J": None, "pi": None, "T": None},
        },
        "Phase_volume": {"0": None},
    },
    "15N": {
        "Atom_mass": 16,
        "Z": 7,
        "N": 8,
        "Mass_MeV": 14084.3256317,
        "Mass_amu": 15.000108898266,
        "E_binding": 0.101,
        "Energy_lvl": {
            "0": {"E_x": 0, "J": 0.5, "pi": 1, "T": None},
            "1": {"E_x": 15, "J": None, "pi": None, "T": None},
            "2": {"E_x": 20, "J": None, "pi": None, "T": None},
        },
        "Phase_volume": {"0": None},
    },
    "16N": {
        "Atom_mass": 16,
        "Z": 7,
        "N": 9,
        "Mass_MeV": 15018.308962079998,
        "Mass_amu": 16.0061019,
        "E_binding": 5.683,
        "Energy_lvl": {
            "0": {"E_x": 0, "J": 0.5, "pi": 1, "T": None},
            "1": {"E_x": 15, "J": None, "pi": None, "T": None},
            "2": {"E_x": 20, "J": None, "pi": None, "T": None},
        },
        "Phase_volume": {"0": None},
    },
    "17N": {
        "Atom_mass": 16,
        "Z": 7,
        "N": 10,
        "Mass_MeV": 15955.68729246,
        "Mass_amu": 17.008449,
        "E_binding": 7.870,
        "Energy_lvl": {
            "0": {"E_x": 0, "J": 0.5, "pi": 1, "T": None},
            "1": {"E_x": 15, "J": None, "pi": None, "T": None},
            "2": {"E_x": 20, "J": None, "pi": None, "T": None},
        },
        "Phase_volume": {"0": None},
    },
    "18N": {
        "Atom_mass": 16,
        "Z": 7,
        "N": 11,
        "Mass_MeV": 16890.00962284,
        "Mass_amu": 18.014078,
        "E_binding": 13.113,
        "Energy_lvl": {
            "0": {"E_x": 0, "J": 0.5, "pi": 1, "T": None},
            "1": {"E_x": 15, "J": None, "pi": None, "T": None},
            "2": {"E_x": 20, "J": None, "pi": None, "T": None},
        },
        "Phase_volume": {"0": None},
    },
    "19N": {
        "Atom_mass": 16,
        "Z": 7,
        "N": 12,
        "Mass_MeV": 17826.83195322,
        "Mass_amu": 19.017022,
        "E_binding": 15.856,
        "Energy_lvl": {
            "0": {"E_x": 0, "J": 0.5, "pi": 1, "T": None},
            "1": {"E_x": 15, "J": None, "pi": None, "T": None},
            "2": {"E_x": 20, "J": None, "pi": None, "T": None},
        },
        "Phase_volume": {"0": None},
    },
    "11O": {
        "Atom_mass": 11,
        "Z": 8,
        "N": 3,
        "Mass_MeV": 17826.83195322,
        "Mass_amu": 11.05125,
        "E_binding": 15.856,
        "Energy_lvl": {
            "0": {"E_x": 0, "J": 0.5, "pi": 1, "T": None},
            "1": {"E_x": 15, "J": None, "pi": None, "T": None},
            "2": {"E_x": 20, "J": None, "pi": None, "T": None},
        },
        "Phase_volume": {"0": None},
    },
    "12O": {
        "Atom_mass": 12,
        "Z": 8,
        "N": 4,
        "Mass_MeV": 17826.83195322,
        "Mass_amu": 12.034368,
        "E_binding": 15.856,
        "Energy_lvl": {
            "0": {"E_x": 0, "J": 0.5, "pi": 1, "T": None},
            "1": {"E_x": 15, "J": None, "pi": None, "T": None},
            "2": {"E_x": 20, "J": None, "pi": None, "T": None},
        },
        "Phase_volume": {"0": None},
    },
    "13O": {
        "Atom_mass": 13,
        "Z": 8,
        "N": 5,
        "Mass_MeV": 17826.83195322,
        "Mass_amu": 13.024815,
        "E_binding": 15.856,
        "Energy_lvl": {
            "0": {"E_x": 0, "J": 0.5, "pi": 1, "T": None},
            "1": {"E_x": 15, "J": None, "pi": None, "T": None},
            "2": {"E_x": 20, "J": None, "pi": None, "T": None},
        },
        "Phase_volume": {"0": None},
    },
    "14O": {
        "Atom_mass": 14,
        "Z": 8,
        "N": 6,
        "Mass_MeV": 17826.83195322,
        "Mass_amu": 14.008596706,
        "E_binding": 15.856,
        "Energy_lvl": {
            "0": {"E_x": 0, "J": 0.5, "pi": 1, "T": None},
            "1": {"E_x": 15, "J": None, "pi": None, "T": None},
            "2": {"E_x": 20, "J": None, "pi": None, "T": None},
        },
        "Phase_volume": {"0": None},
    },
    "15O": {
        "Atom_mass": 15,
        "Z": 8,
        "N": 7,
        "Mass_MeV": 17826.83195322,
        "Mass_amu": 15.0030656,
        "E_binding": 15.856,
        "Energy_lvl": {
            "0": {"E_x": 0, "J": 0.5, "pi": 1, "T": None},
            "1": {"E_x": 15, "J": None, "pi": None, "T": None},
            "2": {"E_x": 20, "J": None, "pi": None, "T": None},
        },
        "Phase_volume": {"0": None},
    },
    "16O": {
        "Atom_mass": 16,
        "Z": 8,
        "N": 8,
        "Mass_MeV": 14899.16083772,
        "Mass_amu": 15.99491461956,
        "E_binding": -4.737,
        "Energy_lvl": {
            "0": {"E_x": 0, "J": 0.5, "pi": 1, "T": None},
            "1": {"E_x": 15, "J": None, "pi": None, "T": None},
            "2": {"E_x": 20, "J": None, "pi": None, "T": None},
        },
        "Phase_volume": {"0": None},
    },
    "17O": {
        "Atom_mass": 17,
        "Z": 8,
        "N": 9,
        "Mass_MeV": 17826.83195322,
        "Mass_amu": 16.999131755953,
        "E_binding": 15.856,
        "Energy_lvl": {
            "0": {"E_x": 0, "J": 0.5, "pi": 1, "T": None},
            "1": {"E_x": 15, "J": None, "pi": None, "T": None},
            "2": {"E_x": 20, "J": None, "pi": None, "T": None},
        },
        "Phase_volume": {"0": None},
    },
    "18O": {
        "Atom_mass": 18,
        "Z": 8,
        "N": 10,
        "Mass_MeV": 17826.83195322,
        "Mass_amu": 17.999159612136,
        "E_binding": 15.856,
        "Energy_lvl": {
            "0": {"E_x": 0, "J": 0.5, "pi": 1, "T": None},
            "1": {"E_x": 15, "J": None, "pi": None, "T": None},
            "2": {"E_x": 20, "J": None, "pi": None, "T": None},
        },
        "Phase_volume": {"0": None},
    },
    "19O": {
        "Atom_mass": 19,
        "Z": 8,
        "N": 11,
        "Mass_MeV": 17826.83195322,
        "Mass_amu": 19.0035780,
        "E_binding": 15.856,
        "Energy_lvl": {
            "0": {"E_x": 0, "J": 0.5, "pi": 1, "T": None},
            "1": {"E_x": 15, "J": None, "pi": None, "T": None},
            "2": {"E_x": 20, "J": None, "pi": None, "T": None},
        },
        "Phase_volume": {"0": None},
    },
    "20O": {
        "Atom_mass": 20,
        "Z": 8,
        "N": 12,
        "Mass_MeV": 17826.83195322,
        "Mass_amu": 20.0040754,
        "E_binding": 15.856,
        "Energy_lvl": {
            "0": {"E_x": 0, "J": 0.5, "pi": 1, "T": None},
            "1": {"E_x": 15, "J": None, "pi": None, "T": None},
            "2": {"E_x": 20, "J": None, "pi": None, "T": None},
        },
        "Phase_volume": {"0": None},
    },
    "21O": {
        "Atom_mass": 21,
        "Z": 8,
        "N": 13,
        "Mass_MeV": 17826.83195322,
        "Mass_amu": 21.008655,
        "E_binding": 15.856,
        "Energy_lvl": {
            "0": {"E_x": 0, "J": 0.5, "pi": 1, "T": None},
            "1": {"E_x": 15, "J": None, "pi": None, "T": None},
            "2": {"E_x": 20, "J": None, "pi": None, "T": None},
        },
        "Phase_volume": {"0": None},
    },
    "22O": {
        "Atom_mass": 22,
        "Z": 8,
        "N": 14,
        "Mass_MeV": 17826.83195322,
        "Mass_amu": 22.00997,
        "E_binding": 15.856,
        "Energy_lvl": {
            "0": {"E_x": 0, "J": 0.5, "pi": 1, "T": None},
            "1": {"E_x": 15, "J": None, "pi": None, "T": None},
            "2": {"E_x": 20, "J": None, "pi": None, "T": None},
        },
        "Phase_volume": {"0": None},
    },
    "23O": {
        "Atom_mass": 23,
        "Z": 8,
        "N": 15,
        "Mass_MeV": 17826.83195322,
        "Mass_amu": 23.01570,
        "E_binding": 15.856,
        "Energy_lvl": {
            "0": {"E_x": 0, "J": 0.5, "pi": 1, "T": None},
            "1": {"E_x": 15, "J": None, "pi": None, "T": None},
            "2": {"E_x": 20, "J": None, "pi": None, "T": None},
        },
        "Phase_volume": {"0": None},
    },
    "17F": {
        "Atom_mass": 17,
        "Z": 9,
        "N": 8,
        "Mass_MeV": 15837.34315214,
        "Mass_amu": 17.002095237,
        "E_binding": 1.952,
        "Energy_lvl": {
            "0": {"E_x": 0, "J": None, "pi": 1, "T": None},
            "1": {"E_x": 0.4953, "J": None, "pi": None, "T": None},
            "2": {"E_x": 3.104, "J": None, "pi": None, "T": None},
            "3": {"E_x": 3.857, "J": None, "pi": None, "T": None},
            "4": {"E_x": 4.64, "J": None, "pi": None, "T": None},
            "5": {"E_x": 5.00, "J": None, "pi": None, "T": None},
            "6": {"E_x": 5.22, "J": None, "pi": None, "T": None},
            "7": {"E_x": 5.49, "J": None, "pi": None, "T": None},
            "8": {"E_x": 6.04, "J": None, "pi": None, "T": None},
            "9": {"E_x": 6.56, "J": None, "pi": None, "T": None},
            "10": {"E_x": 7.03, "J": None, "pi": None, "T": None},
            "11": {"E_x": 7.48, "J": None, "pi": None, "T": None},
            "12": {"E_x": 8.08, "J": None, "pi": None, "T": None},
            "13": {"E_x": 8.38, "J": None, "pi": None, "T": None},
            "14": {"E_x": 8.75, "J": None, "pi": None, "T": None},
            "15": {"E_x": 9.17, "J": None, "pi": None, "T": None},
        },
        "Phase_volume": {"0": None},
    },
    "24O": {
        "Atom_mass": 24,
        "Z": 8,
        "N": 16,
        "Mass_MeV": 17826.83195322,
        "Mass_amu": 24.01986,
        "E_binding": 15.856,
        "Energy_lvl": {
            "0": {"E_x": 0, "J": 0.5, "pi": 1, "T": None},
            "1": {"E_x": 15, "J": None, "pi": None, "T": None},
            "2": {"E_x": 20, "J": None, "pi": None, "T": None},
        },
        "Phase_volume": {"0": None},
    },
}
